In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("/Users/sreeharivenkataraman/Personal Files/DS_Projects/project_2/dataset/ONLINE_FOOD_DELIVERY_ANALYSIS.csv")
df

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,NaN,Central,RES936,Restaurant_29,Chinese,10/20/2024,...,NaN,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,NaN,Female,Chennai,North,RES689,Restaurant_419,Chinese,8/12/2024,...,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,NaN,Male,Delhi,NaN,RES723,Restaurant_244,Arabian,12/8/2024,...,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,NaN,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10/8/2024,...,NaN,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,NaN,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2/4/2024,...,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD099996,CUST3722,NaN,NaN,Mumbai,NaN,RES295,Restaurant_500,Arabian,6/10/2024,...,132.0,Card,Delivered,NaN,DP835,2.0,4.0,Weekday,True,0.17
99996,ORD099997,CUST6158,NaN,Male,Mumbai,East,RES157,Restaurant_458,Arabian,4/22/2024,...,1078.0,NaN,Delivered,NaN,DP476,4.0,3.5,Weekday,False,-0.15
99997,ORD099998,CUST2155,NaN,NaN,Delhi,East,RES287,Restaurant_273,NaN,2/23/2024,...,NaN,COD,Cancelled,NaN,DP577,2.0,4.0,Weekday,True,0.47
99998,ORD099999,CUST3015,NaN,Female,Delhi,North,RES491,Restaurant_241,NaN,12/10/2024,...,NaN,NaN,Delivered,NaN,DP896,NaN,4.3,Weekday,NaN,0.44
99999,ORD100000,CUST7959,NaN,Other,Hyderabad,East,RES680,Restaurant_237,Chinese,NaN,...,NaN,Wallet,Cancelled,NaN,DP908,5.0,4.2,Weekday,False,0.20

In [7]:
df.shape

(100000, 25)

In [8]:
df.isnull()

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,False,False,False,False,True,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,False,False,True,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,False,False,True,True,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
99996,False,False,True,False,False,False,False,False,False,False,...,False,True,False,True,False,False,False,False,False,False
99997,False,False,True,True,False,False,False,False,True,False,...,True,False,False,True,False,False,False,False,False,False
99998,False,False,True,False,False,False,False,False,True,False,...,True,True,False,True,False,True,False,False,True,False
99999,False,False,True,False,False,False,False,False,False,True,...,True,False,False,True,False,False,False,False,False,False

In [9]:
df.isnull().sum()

Order_ID                   0
Customer_ID                0
Customer_Age           50093
Customer_Gender        24856
City                   16726
Area                   16685
Restaurant_ID              0
Restaurant_Name            0
Cuisine_Type           16885
Order_Date              1014
Order_Time              1998
Delivery_Time_Min      33359
Distance_km            33470
Order_Value            33327
Discount_Applied       16715
Final_Amount           55697
Payment_Mode           19911
Order_Status               0
Cancellation_Reason    90969
Delivery_Partner_ID        0
Delivery_Rating        16523
Restaurant_Rating          0
Order_Day                  0
Peak_Hour              32962
Profit_Margin              0
dtype: int64

In [10]:
df.describe()

,Customer_Age,Delivery_Time_Min,Distance_km,Order_Value,Discount_Applied,Final_Amount,Delivery_Rating,Restaurant_Rating,Profit_Margin
count,49907.000000,66641.000000,66530.000000,66673.000000,83285.000000,44303.000000,83477.000000,100000.000000,100000.000000
mean,38.976516,127.475923,16.449242,2081.830126,93.936243,1961.101190,2.991531,4.249680,0.150362
std,12.372157,90.805839,12.256742,1553.628891,108.209904,1557.354417,1.414108,0.722554,0.201888
min,18.000000,20.000000,1.000000,150.000000,0.000000,-150.000000,1.000000,3.000000,-0.200000
25%,28.000000,45.000000,5.470000,673.000000,20.000000,559.000000,2.000000,3.600000,-0.020000
50%,39.000000,120.000000,9.970000,1197.000000,50.000000,1156.000000,3.000000,4.200000,0.150000
75%,50.000000,210.000000,27.430000,3494.000000,100.000000,3375.000000,4.000000,4.900000,0.320000
max,60.000000,300.000000,40.000000,5000.000000,300.000000,4980.000000,5.000000,5.500000,0.500000

In [11]:
df.columns.to_list()

['Order_ID',
 'Customer_ID',
 'Customer_Age',
 'Customer_Gender',
 'City',
 'Area',
 'Restaurant_ID',
 'Restaurant_Name',
 'Cuisine_Type',
 'Order_Date',
 'Order_Time',
 'Delivery_Time_Min',
 'Distance_km',
 'Order_Value',
 'Discount_Applied',
 'Final_Amount',
 'Payment_Mode',
 'Order_Status',
 'Cancellation_Reason',
 'Delivery_Partner_ID',
 'Delivery_Rating',
 'Restaurant_Rating',
 'Order_Day',
 'Peak_Hour',
 'Profit_Margin']

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             100000 non-null  str
 1   Customer_ID          100000 non-null  str
 2   Customer_Age         49907 non-null   float64
 3   Customer_Gender      75144 non-null   str
 4   City                 83274 non-null   str
 5   Area                 83315 non-null   str
 6   Restaurant_ID        100000 non-null  str
 7   Restaurant_Name      100000 non-null  str
 8   Cuisine_Type         83115 non-null   str
 9   Order_Date           98986 non-null   str
 10  Order_Time           98002 non-null   str
 11  Delivery_Time_Min    66641 non-null   float64
 12  Distance_km          66530 non-null   float64
 13  Order_Value          66673 non-null   float64
 14  Discount_Applied     83285 non-null   float64
 15  Final_Amount         44303 non-null   float64
 16  Payment_Mode         80089 non-null   str
 17  Order_Status         100000 non-null  str
 18  Cancellation_Reason  9031 non-null    str
 19  Delivery_Partner_ID  100000 non-null  str
 20  Delivery_Rating      83477 non-null   float64
 21  Restaurant_Rating    100000 non-null  float64
 22  Order_Day            100000 non-null  str
 23  Peak_Hour            67038 non-null   object
 24  Profit_Margin        100000 non-null  float64
dtypes: float64(9), object(1), str(15)
memory usage: 28.2+ MB

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.nunique()

Order_ID               100000
Customer_ID              8999
Customer_Age               43
Customer_Gender             3
City                        5
Area                        5
Restaurant_ID             900
Restaurant_Name           500
Cuisine_Type                5
Order_Date                365
Order_Time                  1
Delivery_Time_Min         232
Distance_km              3402
Order_Value              4052
Discount_Applied            5
Final_Amount             4574
Payment_Mode                4
Order_Status                2
Cancellation_Reason         3
Delivery_Partner_ID       900
Delivery_Rating             5
Restaurant_Rating          26
Order_Day                   2
Peak_Hour                   2
Profit_Margin              71
dtype: int64

In [15]:
missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})

missing

                     Missing_Count  Missing_Percentage
Order_ID                         0                0.00
Customer_ID                      0                0.00
Customer_Age                 50093               50.09
Customer_Gender              24856               24.86
City                         16726               16.73
Area                         16685               16.68
Restaurant_ID                    0                0.00
Restaurant_Name                  0                0.00
Cuisine_Type                 16885               16.89
Order_Date                    1014                1.01
Order_Time                    1998                2.00
Delivery_Time_Min            33359               33.36
Distance_km                  33470               33.47
Order_Value                  33327               33.33
Discount_Applied             16715               16.72
Final_Amount                 55697               55.70
Payment_Mode                 19911               19.91
Order_Status                     0                0.00
Cancellation_Reason          90969               90.97
Delivery_Partner_ID              0                0.00
Delivery_Rating              16523               16.52
Restaurant_Rating                0                0.00
Order_Day                        0                0.00
Peak_Hour                    32962               32.96
Profit_Margin                    0                0.00

In [16]:
missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})

missing = missing[missing["Missing_Count"] > 0]

missing

                     Missing_Count  Missing_Percentage
Customer_Age                 50093               50.09
Customer_Gender              24856               24.86
City                         16726               16.73
Area                         16685               16.68
Cuisine_Type                 16885               16.89
Order_Date                    1014                1.01
Order_Time                    1998                2.00
Delivery_Time_Min            33359               33.36
Distance_km                  33470               33.47
Order_Value                  33327               33.33
Discount_Applied             16715               16.72
Final_Amount                 55697               55.70
Payment_Mode                 19911               19.91
Cancellation_Reason          90969               90.97
Delivery_Rating              16523               16.52
Peak_Hour                    32962               32.96

In [17]:
missing.sort_values(
    by="Missing_Percentage",
    ascending=False
)

                     Missing_Count  Missing_Percentage
Cancellation_Reason          90969               90.97
Final_Amount                 55697               55.70
Customer_Age                 50093               50.09
Distance_km                  33470               33.47
Delivery_Time_Min            33359               33.36
Order_Value                  33327               33.33
Peak_Hour                    32962               32.96
Customer_Gender              24856               24.86
Payment_Mode                 19911               19.91
Cuisine_Type                 16885               16.89
City                         16726               16.73
Discount_Applied             16715               16.72
Area                         16685               16.68
Delivery_Rating              16523               16.52
Order_Time                    1998                2.00
Order_Date                    1014                1.01

In [18]:
missing_sorted = missing.sort_values(
    by="Missing_Percentage",
    ascending=False
).reset_index().rename(columns={"index": "Column_Name"})

missing_sorted.index = missing_sorted.index + 1
missing_sorted.index.name = "S.No"
missing_sorted

              Column_Name  Missing_Count  Missing_Percentage
S.No
1     Cancellation_Reason          90969               90.97
2            Final_Amount          55697               55.70
3            Customer_Age          50093               50.09
4             Distance_km          33470               33.47
5       Delivery_Time_Min          33359               33.36
6             Order_Value          33327               33.33
7               Peak_Hour          32962               32.96
8         Customer_Gender          24856               24.86
9            Payment_Mode          19911               19.91
10           Cuisine_Type          16885               16.89
11                   City          16726               16.73
12       Discount_Applied          16715               16.72
13                   Area          16685               16.68
14        Delivery_Rating          16523               16.52
15             Order_Time           1998                2.00
16             Order_Date           1014                1.01

In [19]:
pip install matplotlib

Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (2.5.3)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [32]:
df["Restaurant_Rating"].value_counts()

Restaurant_Rating
4.4    4088
3.6    4085
3.8    4080
5.2    4054
3.1    4047
4.3    4041
4.7    4035
4.2    4032
5.1    4031
5.0    4024
5.3    4016
3.4    4005
3.2    3985
4.1    3984
4.9    3980
3.7    3980
4.0    3975
3.5    3969
3.9    3966
4.5    3955
4.8    3927
4.6    3917
3.3    3904
5.4    3876
5.5    2042
3.0    2002
Name: count, dtype: int64

In [39]:
df["Restaurant_Rating"].describe()

count    100000.000000
mean          4.249680
std           0.722554
min           3.000000
25%           3.600000
50%           4.200000
75%           4.900000
max           5.500000
Name: Restaurant_Rating, dtype: float64

In [40]:
df["Profit_Margin"].value_counts()

Profit_Margin
 0.26    1513
 0.00    1506
 0.25    1502
 0.32    1501
 0.14    1479
         ...
 0.41    1362
 0.02    1349
 0.48    1334
 0.50     760
-0.20     732
Name: count, Length: 71, dtype: int64

In [41]:
df["Final_Amount"].value_counts()

Final_Amount
 338.0     37
 512.0     35
 722.0     33
 716.0     33
 754.0     33
           ..
-139.0      1
 1724.0     1
 1702.0     1
 1881.0     1
 1851.0     1
Name: count, Length: 4574, dtype: int64

In [43]:
pd.set_option('display.max_columns', None)
df.head()

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,Order_Time,Delivery_Time_Min,Distance_km,Order_Value,Discount_Applied,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,NaN,Central,RES936,Restaurant_29,Chinese,10/20/2024,0:00,187.0,15.75,NaN,NaN,NaN,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,NaN,Female,Chennai,North,RES689,Restaurant_419,Chinese,8/12/2024,0:00,20.0,29.50,4869.0,20.0,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,NaN,Male,Delhi,NaN,RES723,Restaurant_244,Arabian,12/8/2024,0:00,207.0,NaN,757.0,20.0,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,NaN,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10/8/2024,0:00,143.0,15.68,NaN,NaN,NaN,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,NaN,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2/4/2024,0:00,51.0,9.60,372.0,20.0,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12

In [44]:
df["Order_Status"].value_counts()

Order_Status
Delivered    84964
Cancelled    15036
Name: count, dtype: int64

In [48]:
df.loc[df["Order_Status"] == "Cancelled",["Order_Status","Cancellation_Reason"]]

      Order_Status Cancellation_Reason
3        Cancelled       Late Delivery
15       Cancelled    Restaurant Issue
31       Cancelled                 NaN
36       Cancelled  Customer Cancelled
38       Cancelled                 NaN
...            ...                 ...
99960    Cancelled       Late Delivery
99985    Cancelled                 NaN
99994    Cancelled                 NaN
99997    Cancelled                 NaN
99999    Cancelled                 NaN

[15036 rows x 2 columns]

In [49]:
df["Order_Time"].value_counts()

Order_Time
0:00    98002
Name: count, dtype: int64

In [50]:
df["Peak_Hour"].value_counts()

Peak_Hour
False    33585
True     33453
Name: count, dtype: int64

In [52]:
df["Order_Day"].value_counts()

Order_Day
Weekday    71370
Weekend    28630
Name: count, dtype: int64

In [53]:
df_clean = df.copy()

In [54]:
missing = df_clean.isnull().sum()

missing = missing[missing > 0]

missing_percentage = (
    missing / len(df_clean) * 100
).round(2)

missing_df = pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": missing_percentage
})

missing_df.sort_values(
    by="Missing_Percentage",
    ascending=False
)

                     Missing_Count  Missing_Percentage
Cancellation_Reason          90969               90.97
Final_Amount                 55697               55.70
Customer_Age                 50093               50.09
Distance_km                  33470               33.47
Delivery_Time_Min            33359               33.36
Order_Value                  33327               33.33
Peak_Hour                    32962               32.96
Customer_Gender              24856               24.86
Payment_Mode                 19911               19.91
Cuisine_Type                 16885               16.89
City                         16726               16.73
Discount_Applied             16715               16.72
Area                         16685               16.68
Delivery_Rating              16523               16.52
Order_Time                    1998                2.00
Order_Date                    1014                1.01

In [55]:
df_clean["Customer_Age"] = (
    df_clean["Customer_Age"]
    .fillna(df_clean["Customer_Age"].median())
)

In [56]:
df_clean["Customer_Gender"] = (
    df_clean["Customer_Gender"]
    .fillna("Unknown")
)

In [57]:
df_clean["City"] = df_clean["City"].fillna("Unknown")

df_clean["Area"] = df_clean["Area"].fillna("Unknown")

df_clean["Cuisine_Type"] = (
    df_clean["Cuisine_Type"].fillna("Unknown")
)

In [58]:
df_clean["Payment_Mode"] = (
    df_clean["Payment_Mode"]
    .fillna("Unknown")
)

In [59]:
df_clean["Order_Value"] = (
    df_clean["Order_Value"]
    .fillna(df_clean["Order_Value"].median())
)

In [60]:
df_clean["Discount_Applied"] = (
    df_clean["Discount_Applied"]
    .fillna(df_clean["Discount_Applied"].median())
)

In [61]:
df_clean["Final_Amount"] = (
    df_clean["Order_Value"]
    - df_clean["Discount_Applied"]
)

In [62]:
df_clean["Distance_km"] = (
    df_clean["Distance_km"]
    .fillna(df_clean["Distance_km"].median())
)

In [63]:
df_clean["Delivery_Time_Min"] = (
    df_clean["Delivery_Time_Min"]
    .fillna(df_clean["Delivery_Time_Min"].median())
)

In [64]:
delivered_mask = df_clean["Order_Status"] == "Delivered"

median_rating = df_clean.loc[
    delivered_mask,
    "Delivery_Rating"
].median()

df_clean.loc[
    delivered_mask & df_clean["Delivery_Rating"].isna(),
    "Delivery_Rating"
] = median_rating

In [65]:
df_clean.loc[
    df_clean["Order_Status"] == "Delivered",
    "Cancellation_Reason"
] = "Not Applicable"

In [66]:
df_clean.loc[
    (df_clean["Order_Status"] == "Cancelled") &
    (df_clean["Cancellation_Reason"].isna()),
    "Cancellation_Reason"
] = "Unknown"

In [67]:
df_clean["Peak_Hour"] = (
    df_clean["Peak_Hour"]
    .fillna("Unknown")
)

In [68]:
df_clean["Order_Time"] = (
    df_clean["Order_Time"].fillna("0:00")
)

In [69]:
df_clean["Order_Date"] = pd.to_datetime(
    df_clean["Order_Date"],
    errors="coerce"
)

In [70]:
monthly_df = df_clean.dropna(
    subset=["Order_Date"]
)

In [71]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             100000 non-null  str
 1   Customer_ID          100000 non-null  str
 2   Customer_Age         100000 non-null  float64
 3   Customer_Gender      100000 non-null  str
 4   City                 100000 non-null  str
 5   Area                 100000 non-null  str
 6   Restaurant_ID        100000 non-null  str
 7   Restaurant_Name      100000 non-null  str
 8   Cuisine_Type         100000 non-null  str
 9   Order_Date           98986 non-null   datetime64[us]
 10  Order_Time           100000 non-null  str
 11  Delivery_Time_Min    100000 non-null  float64
 12  Distance_km          100000 non-null  float64
 13  Order_Value          100000 non-null  float64
 14  Discount_Applied     100000 non-null  float64
 15  Final_Amount         100000 non-null  float64
 16  Payment_Mode         100000 non-null  str
 17  Order_Status         100000 non-null  str
 18  Cancellation_Reason  100000 non-null  str
 19  Delivery_Partner_ID  100000 non-null  str
 20  Delivery_Rating      97525 non-null   float64
 21  Restaurant_Rating    100000 non-null  float64
 22  Order_Day            100000 non-null  str
 23  Peak_Hour            100000 non-null  object
 24  Profit_Margin        100000 non-null  float64
dtypes: datetime64[us](1), float64(9), object(1), str(14)
memory usage: 29.1+ MB

In [72]:
df_clean.isnull().sum()

Order_ID                  0
Customer_ID               0
Customer_Age              0
Customer_Gender           0
City                      0
Area                      0
Restaurant_ID             0
Restaurant_Name           0
Cuisine_Type              0
Order_Date             1014
Order_Time                0
Delivery_Time_Min         0
Distance_km               0
Order_Value               0
Discount_Applied          0
Final_Amount              0
Payment_Mode              0
Order_Status              0
Cancellation_Reason       0
Delivery_Partner_ID       0
Delivery_Rating        2475
Restaurant_Rating         0
Order_Day                 0
Peak_Hour                 0
Profit_Margin             0
dtype: int64

In [73]:
df_clean["Delivery_Rating"].value_counts()

Delivery_Rating
3.0    30456
2.0    16896
4.0    16885
1.0    16818
5.0    16470
Name: count, dtype: int64

In [74]:
df_clean.loc[
    df_clean["Order_Status"] == "Cancelled",
    "Delivery_Rating"
] = np.nan

In [75]:
df_clean.to_csv(
    "online_food_delivery_cleaned.csv",
    index=False
)